# AsREPRoasting Amelia
- name: Disable Kerberos-PreAuthentication for Amelia
  ansible.windows.win_powershell:
    script: |
      Set-ADAccountControl -Identity amelia.doppler -DoesNotRequirePreAuth $true
