- name: Enable RDP
  ansible.windows.win_regedit:
    key: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    type: dword
    data: 0

- name: Allow remote desktop connections for all users
  ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
      name: UserAuthentication
      data: 0
      type: dword

- name: Allow local users to log on remotely
  ansible.windows.win_user_right:
    name: SeRemoteInteractiveLogonRight
    users: BUILTIN\Users
    action: add

- name: Allow Navy IT to log on remotely
  ansible.windows.win_user_right:
    name: SeRemoteInteractiveLogonRight
    users:
      - Navy IT
    action: add
    
- name: Add Navy IT to Remote Desktop Users group
  ansible.windows.win_shell: net localgroup "Remote Desktop Users" "Navy IT" /add
  ignore_errors: true

- name: Add Navy IT to Remote Management group (Used for winrm)
  ansible.windows.win_shell: net localgroup "Remote Management Users" "Navy IT" /add
  ignore_errors: true
