- name: Building PortRoyal...
  hosts: portroyal
  gather_facts: true
  tags: light
  vars_files:
    - vars-chest.yml
  roles:
  - role: SetHostname
  - role: DeployAD
  - role: SetPasswordPolicy
  - role: SetTimeZone
  - role: SetFirewallState
  - role: SetDefenderOff
  - role: OrganizeRoyalNavy
  - role: RecruitNavySailors
  - role: Kerberoast
  - role: ASREPRoast
  - role: LLMNRPoisoning
  - role: EnableDomainGuest
  - role: SMBRoyalShare
  - role: EnableRDP

- name: Launching workstations
  hosts: workstations
  gather_facts: true
  vars_files:
    - vars-chest.yml
  roles:
  - role: DomainJoinComputer

- name: Admin tasks on DAUNTLESS & INTERCEPTOR
  hosts: domain_workstations
  roles:
  - role: SetFirewallState
  - role: SetDefenderOff
  - role: EnableRDP

- name: Admin tasks on DAUNTLESS
  hosts: admin-dauntless
  roles:
  - role: SetLocalAdmin

- name: Admin tasks on INTERCEPTOR
  hosts: admin-interceptor
  roles:
  - role: SetLocalAdmin
