- name: Building PortRoyal...
  hosts: portroyal
  gather_facts: true
  tags: light
  vars_files:
    - vars-chest.yml
  roles:
  - role: SetHostname
  - role: DeployAD
  - role: SetPasswordPolicy
  - role: SetTimeZone
  - role: SetFirewallState
  - role: SetDefenderOff
  - role: OrganizeRoyalNavy
  - role: RecruitNavySailors
  - role: Kerberoast
  - role: ASREPRoast
  - role: LLMNRPoisoning
  - role: SetExtendedACL
  - role: EnableDomainGuest
  - role: SMBRoyalShare
  - role: EnableRemoting

- name: Launching Dauntless
  hosts: dauntless
  gather_facts: true
  tags: workstations
  vars_files:
    - vars-chest.yml
  vars:    
    hostname: "DAUNTLESS"
  roles:
  - role: DomainJoinComputer

- name: Launching Interceptor
  hosts: interceptor
  gather_facts: true
  tags: workstations
  vars_files:
    - vars-chest.yml
  vars:
    hostname: "INTERCEPTOR"
  roles:
  - role: DomainJoinComputer

- name: Admin tasks on DAUNTLESS
  hosts: admin-dauntless
  tags: workstations
  roles:
  - role: SetFirewallState
  - role: SetDefenderOff
  - role: EnableRemoting
  - role: SetLocalAdmin

- name: Admin tasks on INTERCEPTOR
  hosts: admin-interceptor
  tags: workstations
  roles:
  - role: SetFirewallState
  - role: SetDefenderOff
  - role: EnableRemoting
#  - role: InstallFirefox
#  - role: UploadFirefoxProfile
