# STOP all updates on windows
- name: Stop Windows Update Service
  ansible.windows.win_service:
    name: wuauserv
    state: stopped
    start_mode: disabled

- name: Disable Windows Update
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU'
    name: NoAutoUpdate
    data: 1
    type: dword
