# Run the extended ACL script (for amelia)
- name: Grant amelia force password over james
  ansible.windows.win_powershell:
    script: |
      $srcobj = (Get-ADUser -Identity "amelia.doppler").sid
      $dstobj = (Get-ADUser -Identity "james.norrington").DistinguishedName
      $ADObject = [ADSI]("LDAP://" + $dstobj)
      $guid = "00299570-246d-11d0-a768-00aa006e0529" 
      $type = [System.Security.AccessControl.AccessControlType] "Allow"
      $inheritanceType = [System.DirectoryServices.ActiveDirectorySecurityInheritance] "All"
      $ACE = New-Object System.DirectoryServices.ExtendedRightAccessRule $srcobj,$type,$guid,$inheritanceType
      $ADObject.psbase.ObjectSecurity.AddAccessRule($ACE)
      $ADObject.psbase.commitchanges()