# https://learn.microsoft.com/en-us/powershell/module/activedirectory/set-addefaultdomainpasswordpolicy?view=windowsserver2025-ps
- name: set password policy
  ansible.windows.win_powershell:
    script: |
      Set-ADDefaultDomainPasswordPolicy -Identity $Domain -LockoutDuration $LockoutDuration -LockoutThreshold $LockoutThreshold -ComplexityEnabled $ComplexityEnabled -ReversibleEncryptionEnabled $False -MinPasswordLength $MinPasswordLength -MaxPasswordAge "10675199.00:00:00"
    error_action: stop
    parameters:
      Domain: "{{ FQDN }}"
      LockoutThreshold: "{{ pass_pol.lockout_threshold }}"
      MinPasswordLength: "{{ pass_pol.pass_length }}"
      LockoutDuration: "{{ pass_pol.lockout_duration }}"
      ComplexityEnabled: "{{ pass_pol.complexity }}"
