# Abhorrent Password Policy
- name: Set Minimum Password Length
  win_security_policy:
    section: System Access
    key: MinimumPasswordLength
    value: "{{ pass_pol.pass_length }}"

- name: Set Minimum Password Age
  win_security_policy:
    section: System Access
    key: MinimumPasswordAge
    value: 0

- name: Set Maximum Password Age
  win_security_policy:
    section: System Access
    key: MaximumPasswordAge
    value: 99

- name: Set Enforce Password History
  win_security_policy:
    section: System Access
    key: PasswordHistorySize
    value: 0

- name: Set Password Complexity Requirements
  win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: "{{ pass_pol.complexity }}"

- name: Set Local Lockout Threshold
  win_shell: "net accounts /lockoutthreshold:{{ pass_pol.lockout_threshold }}"
  args:
    executable: powershell

- name: Set Domain Lockout Threshold
  win_shell: "net accounts /lockoutthreshold:{{ pass_pol.lockout_threshold }} /domain"
  args:
    executable: powershell